name: Run Tests
on: [push, pull_request, workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v2.8.0
    - name: Run Flutter tests
      run: flutter test
      working-directory: ./e_shop